version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
only_commits:
  files:
    - Consoleum/**/*
    - Consoleum.PageObjects/**/*
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
  - cmd: nuget restore
build:
  publish_nuget: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: C1XWdllP3h983mIvodvqrSkPTgZygNPPGjB/p9+bWzvIpQsaS2D1I3/HxqE/2rwS
  on:
    branch: master
notifications:
  - provider: GitHubPullRequest
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true